jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml

The EKS-D base `periodic` job runs every weekday (Monday to Friday) at 10am PST. It runs scripts to check if there are available `yum` updates on the latest EKS Distro base image, and if available, it triggers a new base image build and creates PR's to the respective repos to replace the new image tag in the respective files.

Add periodic to check for updates and build new base image

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml

Run periodic only at the 11am PST.

Change cron to run only at the hour mark

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml

Reverting to running periodic at 10am PST.

Revert to running at 10am PST

---

jobs/aws/eks-distro/docs-postsubmit.yaml
jobs/presets.yaml

N/A
Make docs uploads use regional endpoint

Use regional endpoints for docs uploads

---

jobs/aws/eks-distro-build-tooling/amazon-eks-pod-identity-webhook-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/amazon-eks-pod-identity-webhook-presubmits.yaml
jobs/aws/eks-distro-build-tooling/athens-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/athens-presubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml
jobs/aws/eks-distro-build-tooling/helm-chart-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/helm-chart-presubmits.yaml

Adding jobs to start building amazon-eks-pod-identity-webhook binary for our cluster. Also adding the "tooling" name to our jobs against the eks-distro-build-tooling repo to distinguish them from our eks-distro jobs for our prow badges in both repos.

Add amazon-eks-pod-identity-webhook jobs and rename eks-distro-build-tooling jobs to include 'tooling'

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

Call the script to create PR's for the new builder-base and eks-distro-base image tag which get generated during the postsubmits.

Invoke PR creation script to change base image tags after every new build

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

We need to mount secrets on the jobs for authenticating with Github and `gh` client.

Add secret volume mounts to base postsubmits for Github authentication

---

jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml

Cloning the PR bot accounts to dry-run PR automation in builder-base presubmit.

Add extra refs to presubmit for builder-base PR automation dry run

---

jobs/aws/eks-distro-build-tooling/prometheus-alertmanager-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/prometheus-alertmanager-presubmits.yaml

Adding presubmit and postsubmit jobs to build Alertmanager images.

Add prowjobs for Prometheus Alertmanager

---

jobs/aws/eks-distro-build-tooling/prometheus-postsubmit.yaml
jobs/aws/eks-distro-build-tooling/prometheus-presubmits.yaml

Adding jobs to build Prometheus. Prometheus is a monitoring tool that can be used to monitor the prow stack.

Adding prowjobs to build Prometheus 

---

jobs/aws/eks-distro-build-tooling/github-exporter-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/github-exporter-presubmits.yaml

Add postsubmit and presubmit jobs for GitHub Exporter project.

Add prowjobs for GitHub Exporter

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml

Calling a make target in periodic instead of script to be consistent with other prowjobs.

Use make invocation in periodic for consistency

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml

In presubmits and postsubmits, the `REPO_OWNER` variable is available in the CI environment. But since periodics are not tied to a particular GitHub repo, we need to export the `REPO_OWNER` explicitly. Also we need to clone the aws/eks-distro-build-tooling repo since that is the source of the automation scripts.

Export Github org information in periodic to enable automatic PR creation

---

jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml

Adding linting presubmit to validate prowjobs. A test script will be added on a follow-up PR. When a PR is raised to add new jobs or change existing jobs, the script runs checks to determine if the added jobs have the proper configuration of buckets, clusters, service accounts, `make` targets, `always_run` and `skip_report` flags, etc. These checks are separate for presubmits and postsubmits. The script also outputs the necessary fixes that need to be made.
This presubmit will be an additional validation test for the jobs we add to the prowjobs repo, i.e., it will catch the common errors like incorrect bucketname/cluster for the job type, which a human reviewer may miss when reviewing.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Add linting presubmit for prowjobs

---

jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml

Fixed indentation so that resources are specified under `.spec.containers[].resources`. The requests and limits will now be applied to the container.

Fix indentation to apply resource requirements to job container

---

jobs/aws/eks-distro-build-tooling/prometheus-helm-chart-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/prometheus-helm-chart-presubmits.yaml

Adding presubmit and postsubmit prow jobs to build helm charts for Prometheus.

Adding Prow jobs for Prometheus charts

---

jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml

The linting script, when merged, will be located under `scripts/lint_prowjobs/main.go` (https://github.com/aws/eks-distro-prow-jobs/pull/58#discussion_r552820228). Hence the prowjob needs to be modified to invoke it from there.

Change directory for linting script invocation

---

jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml

This label was causing the Athens proxy to be set for the lint presubmit, which caused the job to run indefinitely long. Removing the label should fix the issue. Also there are no images built by this prowjob so the label is not appropriate.

Remove unwanted label from lint presubmit

---

jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml

It would be a good idea to run `go vet` on the linting code itself to look for errors, prior to running it. Passing in file name since the file is not in GOROOT.

Use go vet to ensure script is linted before running

---

scripts/lint_prowjobs/main.go

- Split up make comparson block into nested if-blocks for appropriate make target testing.
- Skipping checks for kops postsubmit which does not invoke `make` commands
- Printing filenames only if errors found.

Fix make target comparison block, print filenames only for jobs with errors

---

jobs/aws/eks-distro-build-tooling/athens-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/athens-presubmits.yaml
jobs/aws/eks-distro/aws-iam-authenticator-postsubmits.yaml
jobs/aws/eks-distro/aws-iam-authenticator-presubmits.yaml
jobs/aws/eks-distro/coredns-postsubmits.yaml
jobs/aws/eks-distro/coredns-presubmits.yaml
jobs/aws/eks-distro/etcd-postsubmits.yaml
jobs/aws/eks-distro/etcd-presubmits.yaml
jobs/aws/eks-distro/external-attacher-postsubmits.yaml
jobs/aws/eks-distro/external-attacher-presubmits.yaml
jobs/aws/eks-distro/external-provisioner-postsubmits.yaml
jobs/aws/eks-distro/external-provisioner-presubmits.yaml
jobs/aws/eks-distro/external-resizer-postsubmits.yaml
jobs/aws/eks-distro/external-resizer-presubmits.yaml
jobs/aws/eks-distro/external-snapshotter-postsubmits.yaml
jobs/aws/eks-distro/external-snapshotter-presubmits.yaml
jobs/aws/eks-distro/kubernetes-release-postsubmits.yaml
jobs/aws/eks-distro/kubernetes-release-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-postsubmits.yaml
jobs/aws/eks-distro/livenessprobe-presubmits.yaml
jobs/aws/eks-distro/main-presubmits.yaml
jobs/aws/eks-distro/metrics-server-postsubmits.yaml
jobs/aws/eks-distro/metrics-server-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-postsubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-presubmits.yaml

When [this](https://github.com/aws/eks-distro/pull/122) PR is merged, we will have the EKS distro base tag file in a separate file at the root of the repo instead of the individual Makefiles under each project. We should trigger new builds of these projects every time this tag file changes, since it means we have a new base image to build our projects on. This is achieved by adding the tag file to the `run_if_changed` field.

Change prowjob trigger condition for projects depending on eks-distro-base image

---

jobs/aws/eks-distro/kubernetes-1-19-postsubmits.yaml
jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml

Internal
Added presubmit and postsubmit jobs for 1.19. 
These are exact copies of the ones we use for 1.18, but with all references to 1.18 replaced with 1.19. Vivek confirmed that prow doesn't let us use a template for these.
---

Added presubmit and postsubmit jobs for 1.19

---

jobs/aws/eks-distro/cni-presubmits.yaml

Have the CNI presubmit just call the build target because we don't want to save any artifacts from the build. Also, remove the move command to the log artifacts as we will not be using that either.

Have CNI presubmit just call build

---

jobs/aws/eks-distro/main-1-18-postsubmits.yaml
jobs/aws/eks-distro/main-1-19-postsubmits.yaml

This is currently referencing the artifacts bucket in the artifacts account, which the postsubmit service account does not have access to.

Update artifacts bucket for main postsubmits

---

jobs/aws/eks-distro/main-1-18-postsubmits.yaml
jobs/aws/eks-distro/main-1-19-postsubmits.yaml
jobs/aws/eks-distro/main-presubmits.yaml

Main-postsubmits are failing since they run longer than the 2hr default timeout value mentioned [here](https://github.com/kubernetes/test-infra/blob/master/prow/entrypoint/run.go#L164-L167). We can override the timeout values that get applied to the entrypoint pod utility by setting it explicitly in the job's [decoration config](https://github.com/kubernetes/test-infra/blob/master/prow/apis/prowjobs/v1/types.go#L328-L330).

Increase timeout

---

jobs/aws/eks-distro/main-1-18-postsubmits.yaml
jobs/aws/eks-distro/main-1-19-postsubmits.yaml

Modfiying name of the bucket to workaround the kops issue for now. Needs to be merged once S3 bucket is deployed through CDK.
/hold

Modify bucket name for artifacts for postsubmits

---

scripts/lint_prowjobs/main.go

Release postsubmits will be configured to invoke the `release` target in the [root Makefile](https://github.com/aws/eks-distro/blob/main/Makefile), which is the default make target for postsubmits.

Use default postsubmit make target for linting release-postsubmits

---

jobs/aws/eks-distro/release-1-18-postsubmits.yaml
jobs/aws/eks-distro/release-1-19-postsubmits.yaml

The `setup` target is invoked as a [prerequisite](https://github.com/aws/eks-distro/blob/main/Makefile#L70) of the `release` target in the Makefile. Hence we do not need to invoke it separately on the release postsubmits.

Fix make target for release postsubmits

---

scripts/lint_prowjobs/main.go

Release postsubmits will [execute a script](https://github.com/aws/eks-distro-prow-jobs/pull/100/files) instead of invoking the `release` target in the Makefile. Hence we can skip the make target check for these jobs.

Skip make target check for release postsubmits

---

scripts/lint_prowjobs/main.go

The condition should be checked before retrieving the make target, since it would fail on Prowjobs which don't have make commands.

Fix placement of conditional for make target checks

---

.gitignore
jobs/aws/eks-distro/release-1-18-postsubmits.yaml
jobs/aws/eks-distro/release-1-19-postsubmits.yaml

Release job is currently triggering on all postsubmits, it should only run with the release changes.

Trigger release job on release change

---

scripts/lint_prowjobs/main.go

This change supports the renaming of `main-1-*-postsubmits` to `build-1-*-postsubmits`.

Modify make check for postsubmits that perform conformance tests

---

jobs/aws/eks-distro/build-1-18-postsubmits.yaml
jobs/aws/eks-distro/build-1-19-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-18-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-19-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-18-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-19-postsubmits.yaml

Adding resource limits to our heavier prow jobs after upgrading to bigger instances for our cluster. This is after running into issues with two big jobs being scheduled on one node and running into resource issues. This would ensure that Kubernetes schedules these jobs on nodes that have the capacity as described here: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

Add resource limits for big postsubmits jobs

---

jobs/aws/eks-distro-build-tooling/athens-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/athens-presubmits.yaml
jobs/aws/eks-distro-build-tooling/helm-chart-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/helm-chart-presubmits.yaml
jobs/aws/eks-distro-build-tooling/release-tooling-presubmits.yaml
jobs/aws/eks-distro/cni-presubmits.yaml
jobs/aws/eks-distro/main-presubmits.yaml

This fixes the regular expression for job triggers to mean `any file/folder under specified folder`. The configuration we had earlier has always worked since Prow [performs a MatchString check](https://github.com/kubernetes/test-infra/blob/master/prow/config/jobs.go#L303-L311) on the `run_if_changed` regex, and since it finds a matching string (for example, `projects/gomods/athens/`, `helm/`, `release/`, etc), the check passes and the job is triggered. 

Fix job trigger regular expression

---

jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml

Kubernetes presubmits should use go-runner from public ECR

Kubernetes presubmits should use go-runner from public repo

---

.gitignore
jobs/aws/eks-distro-build-tooling/grafana-helm-chart-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/grafana-helm-chart-presubmits.yaml

We are switching from using managed Grafana, to installing and configuring Grafana using the upstream helm chart. This PR adds presubmit and postsubmit jobs for publishing the charts.

Add jobs for Grafana helm chart

---

jobs/aws/eks-distro/build-1-20-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-20-postsubmits.yaml

Two things here:
* Added call to build kubernetes/release to kubernetes presubmit so that go-runner will always be there (maybe)
* Added other 1.20 postsubmit jobs, the key one is the build one so we get go-runner the next time around

Add 1.20 postsubmit jobs

---

jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml

We need to run the postsubmit build before the presubmit will pass

Disable 1.20 presubmit for now

---

jobs/aws/eks-distro/aws-iam-authenticator-1-18-presubmits.yaml
jobs/aws/eks-distro/aws-iam-authenticator-1-19-presubmits.yaml
jobs/aws/eks-distro/coredns-1-18-presubmits.yaml
jobs/aws/eks-distro/coredns-1-19-presubmits.yaml
jobs/aws/eks-distro/metrics-server-1-18-presubmits.yaml
jobs/aws/eks-distro/metrics-server-1-19-presubmits.yaml

Modifying presubmit jobs for coredns, aws-iam-auth and metrics-server to run for every release version based on RELEASE_BRANCH env variable.

Adding release versioned presubmit jobs

---

jobs/aws/eks-distro/attribution-files-periodics.yaml

https://github.com/aws/eks-distro/pull/242 adds attribution generation to eks-distro to allow us to keep these attribution.txt files up to date.  Generating the files requires a bit of setup and to avoid putting this on the developers contributing to eks-distro we decided to introduce a periodic to generate files across all projects and check in any changes.  Checking in changes to attribution files by themselves also gives us a clear audit trail since they will only ever be changed in bot commits.

add attribution-files-periodic to update attribution.txt files 

---

jobs/aws/eks-distro/attribution-files-periodics.yaml

Instead of pulling down the bot's fork, pull down from the aws org to make sure its always up to date.

sync repo from aws org instead of fork

---

jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml

It it worth tightening up the regex to avoid building all versions of kubernetes when any change?

tighten up run_if_changed for kubernetes to only build changed version

---

jobs/aws/eks-distro/kubernetes-1-18-presubmits-tests.yaml
jobs/aws/eks-distro/kubernetes-1-19-presubmits-tests.yaml
jobs/aws/eks-distro/kubernetes-1-20-presubmits-tests.yaml
scripts/lint_prowjobs/main.go

We really only need to run the unit tests when changing the kubernetes version (GIT_TAG) or modifying/adding to the patches.
Will need to make an update to eks-distro to remove `test` from the [build](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/Makefile#L107) target 

only run kubernetes unit tests when neccessary

---

jobs/aws/eks-distro/dev-release-1-18-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-19-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-20-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-18-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-19-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-20-postsubmits.yaml

Use two independent RELEASE files so that development and production builds can be triggered complete independently.

Target environment release file

---

jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml

According to the [module changes](https://golang.org/doc/go1.16#go-command) in Go 1.16, build and run commands do not modify `go.mod` and `go.sum` by default and report an error if these files need to be updated. Module requirements may be adjusted using `go mod tidy`. 

Add module requirements explicitly for Go 1.16

---

go.mod
jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

With this change, the builder-base and eks-distro-base images will get pushed to the corresponding public ECR repos instead of private ECR.

Configure eks-distro-base and builder-base images to be pushed to public ECR repos

---

config/docker-ecr-config.json

Need to add this endpoint so that amazon ECR credential helper can authenticate with public ECR. 

Add public ECR endpoint to credential helper config

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml

The builder-base image build uses the generate-attribution files for npm installs, so we should push a new builder-base image when those files change.

Build new version of builder-base when generate-attribution files change

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

We want to push the builder-base and eks-distro-base images to the `eks-distro-build-tooling` public registry in a verified account.

Configure base image Prowjobs to push to eks-distro-build-tooling ECR public registry

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml

The `scripts` folder has a script to setup pushes of base images to ECR public, so changes to this script might change the way we push to public ECR. So we should trigger the base image builds when we modify it.

Trigger base image jobs when ECR setup script changes

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

Setting default region to us-east-1 to be used in config file

Set default region as env var in prowjobs

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

Moving the ECR setup script to the prowjob definition to align with eks-d prod-release jobs.

Run ECR setup script before invoking make

---

jobs/aws/eks-distro-build-tooling/amazon-eks-pod-identity-webhook-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/amazon-eks-pod-identity-webhook-presubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml
jobs/aws/eks-distro-build-tooling/github-exporter-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/github-exporter-presubmits.yaml
jobs/aws/eks-distro-build-tooling/prometheus-alertmanager-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/prometheus-alertmanager-presubmits.yaml

/hold
We don't need this variable here anymore.

Remove DEVELOPMENT var from build-tooling jobs

---

jobs/aws/eks-distro/build-1-21-postsubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml

* Replace `1-20` references with `1-21`.

Replace 1-20 references in 1-21 jobs

---

jobs/aws/eks-distro/build-1-21-arm64-postsubmits.yaml

I would add these for all versions, but the upstream conformance images for versions less than 1.21 arent really arm64 so they wont work.  This is a good start though.
/hold

add arm based kops cluster post submit

---

jobs/aws/eks-distro-build-tooling/eks-distro-release-tooling-presubmits.yaml

Rename job to clarify purpose and avoid conflicts.

Rename release tooling presubmit to avoid conflicts

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml

Tag update automation needs to be handled for EKS-A build tooling and prowjob repos as well.
/hold

Clone eks-anywhere repos to support automation

---

config/docker-ecr-config.json
jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml

Changing builder-base Prowjobs to use AL2 from public ECR.

Use public ECR AL2 image as Prowjobs runtime

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml

To support building minimal variants we need a local registry to push to.  This shouldnt break existing builds and will give me a way to test out in my branch where I will hardcode the image_repo.

eks-distro-pre: add docker registry to support pushing to local reg

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml
jobs/presets.yaml
scripts/registry-entrypoint.sh

Add proper readiness/liveness probes.  Fix command + args.  Hardcode image_repo to point to local registry
/hold

eks-distro-base: fix presubmit registry sidecar

---

jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml

To validate the s3 artifacts in the presubmit we need to build tars for the images instead of pushing to the registry.  This overrides the image output only for the release project.

kubernetes-presubmit: only push release images to local registry

---

go.mod
go.sum

Resolves [this](https://github.com/aws/eks-distro-prow-jobs/security/dependabot/go.sum/github.com%2Fdgrijalva%2Fjwt-go/open) Dependabot issue

Update go-jwt module to secure version

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml

Clone the EKS Anywhere repo in the Prowjobs to include it in tag update PR automation workflow.

Add eks-anywhere repos to Prowjobs to update base image

---

jobs/aws/eks-distro/coredns-1-18-presubmits.yaml
jobs/aws/eks-distro/coredns-1-19-presubmits.yaml
jobs/aws/eks-distro/coredns-1-20-presubmits.yaml
jobs/aws/eks-distro/coredns-1-21-presubmits.yaml
jobs/aws/eks-distro/etcd-1-18-presubmits.yaml
jobs/aws/eks-distro/etcd-1-19-presubmits.yaml
jobs/aws/eks-distro/etcd-1-20-presubmits.yaml
jobs/aws/eks-distro/etcd-1-21-presubmits.yaml

Working on sync-ing common make file changes from eks-a to eks-d, [here](https://github.com/aws/eks-distro/pull/631). These two projects build local oci tars for both amd64 and arm64 but in presubmit we need to need to ignore the missing arm64 builds since we do not build arm images on presubmit.

coredns and etcd skip arm validation for oci in presubmit

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

We want images to be pushed only by the periodic (when there's a security update for the packages).

Do not trigger eks-distro-base postsubmits automatically

---

jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml
linter/Makefile
linter/main.go

In #252, the logic to generate Prowjobs from templates wil be added. This PR is a precursor to that PR and will invoke the templater logic on that PR before running lint.

Modify lint presubmit to generate prowjobs before linting

---

jobs/presets.yaml

This PR configures the GOPROXY env var for all Prowjobs, regardless of image-building or not.

Set GOPROXY env var for all Prowjobs

---

jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-22-presubmits.yaml
templater/jobs/presubmit/eks-distro/kubernetes-1-X-presubmits.yaml

With the change to the templater we ended up going over the max cpu for a fargate instance.  This brings the total cpu + mem back to what it was before the templater was added.
Note: we probably want to decrease the buildkit resources across the board, but saving that for a future PR to limit the scope here.

fix kuberentes presubmit resources requests

---

jobs/aws/eks-distro/attribution-files-periodics.yaml
templater/jobs/periodic/eks-distro/attribution-files-periodics.yaml

eks-distro attribution: bump timeout up to handle new kube build

---

scripts/buildkitd-entrypoint.sh

This enables garbage collection on the buildkit worker to clean local builds.

Enable garbage collection on buildkit worker

---

jobs/presets.yaml
scripts/buildkitd-entrypoint.sh

Mount BUILDER_BASE_TAG_FILE onto Prowjob pods as ConfigMap so we can refer to it in scripts.

Mount BUILDER_BASE_TAG_FILE onto Prowjob pods as ConfigMap

---

scripts/buildkitd-entrypoint.sh

Reduce Buildkit GC storage to 5 GB

---

jobs/aws/eks-distro-build-tooling/golang-1.15-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1.15-presubmits.yaml

We don't want to run some priv'd tests (such as unshare tests) in the presubmits, as they will fail due to permissions errors int he unpriv'd execution environment. Adding an env var that we can check in the tests to determine wether to run the priv'd tests or not.
Tried using the fargate AWS_EXECUTION_ENV env var to determine this but it's not being set in our cluster.

add skip privd tests env var to golang presubmit

---

jobs/aws/eks-distro-build-tooling/golang-1.15-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1.15-presubmits.yaml

install deps in presub for go build

add dep install to go build presub

---

jobs/aws/eks-distro-build-tooling/golang-1.15-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1.15-presubmits.yaml

use al2 as base for go to avoid dep install issues

use al2 for golang rpm build

---

jobs/aws/eks-distro-build-tooling/golang-1.15-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1.15-presubmits.yaml

need this env var in the pre-sub now that we're running the dry-run of the artifacts sync to s3

add artifacts bucket env var to presubmit

---

jobs/aws/eks-distro-build-tooling/golang-1.16-ARM64-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.16-ARM64-postsubmits.yaml

https://github.com/aws/eks-distro-internal/issues/240
need to make sure the ARM post-submit name is unique

use unique name for go arm64 prow postsubmit

---

jobs/aws/eks-distro-build-tooling/golang-1.15-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.15-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.16-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.16-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.17-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.17-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.18-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.18-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.18-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.15-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.15-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.16-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.16-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.17-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.17-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.18-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.18-ARM64-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.18-PROD-postsubmits.yaml

https://github.com/aws/eks-distro-internal/issues/241
Add post-submits for each version of Go, which will:
- on changes to the `RELEASE` tag for the given version
- execute a build
- upload the built RPMs to the prod actifacts bucket at the path `golang-$VERSION/releases/$RELEASE_NUMBER/RPMS`
We can then use these stable RPMs as the released, prod versions.

add prod release post-submits for Golang

---

jobs/aws/eks-distro-build-tooling/golang-1.15-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.15-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.16-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.16-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.17-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.17-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.18-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1.18-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.15-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.15-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.16-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.16-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.17-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.17-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.18-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.18-PROD-postsubmits.yaml

https://github.com/aws/eks-distro-internal/issues/241
Add release config for Golang release prow jobs, setting the environment variables and service accounts necessary in order to access the prod artifacts bucket.

add prod release config to Go release prow jobs

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/types/types.go
templater/main.go
templater/templates/periodics.yaml
templater/templates/postsubmits.yaml
templater/templates/presubmits.yaml

Builder-base presubmit is too large to run on fargate. This adds support for running presubmit jobs on the postsubmit cluster. Also, the builder-base job runs off al2 directly instead of the previous builder base, support skipping the buildkit check.

Runs builder-base presubmit on postsubmit cluster

---

jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml

Builder base pre does not need install anymore

---

jobs/presets.yaml

Set Fargate profile as env var to identify if running in Fargate.

Set Fargate profile as env var to identify if running in Fargate

---

jobs/aws/eks-distro/attribution-files-periodics.yaml
templater/jobs/periodic/eks-distro/attribution-files-periodics.yaml

The attribution periodic runs in the middle of the day, sometimes leading to churn and confusion if we're in the middle of updating base images or changing things. Moving this to the middle of the night (1am PT) should help reduce these events. 

Move attribution periodic to run at night

---

jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-22-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-23-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-24-presubmits.yaml
templater/jobs/presubmit/eks-distro/kubernetes-1-X-presubmits.yaml

There was a [Prowjob refactor](https://github.com/aws/eks-distro-prow-jobs/pull/401) today to modify the Prowjob command from `make -C projects/X/Y` to `make -C $PROJECT_PATH` and set the `PROJECT_PATH` as an env var similar to how we do it in EKS-A Prowjob. This change was a precursor to enable easier templating of EKS-A Prowjobs using the same templating logic we have for EKS-D. In the Kubernetes presubmits, we have two project paths, one to build the images from the kubernetes/release project, followed by building the kubernetes/kubernetes project. In the refactor, we replaced both project paths with `PROJECT_PATH=projects/kubernetes/release` so we weren't calling make build on kubernetes/kubernetes, so we don't have the output directory.
```bash
mv: cannot stat …
```

Fix project path var for k/k presubmits

---

jobs/aws/eks-distro/livenessprobe-1-21-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-22-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-23-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-24-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-21-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-22-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-23-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-24-presubmits.yaml
templater/jobs/presubmit/eks-distro/livenessprobe-1-X-presubmits.yaml
templater/jobs/presubmit/eks-distro/node-driver-registrar-1-X-presubmits.yaml

We can, and should, build the windows containers in presubmit because the manifest handling is pretty specific.  We cant do this on the presubmit node due to space issues.

Sets csi sidecar to run on postsubmit cluster

---

templater/jobs/types/types.go

EKS-A prow jobs has some prow jobs which needs to be configured in minimal config thus adding bucket in the types.go jobConfig struct. 

add bucket in jobConfig to use in eks-A templater

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9.yaml

Now that these are running on the minimal builder we do not need the prune.

Removes buildctl prune from distro presubmit

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16.yaml

The layer which contains the nodejs runtime/compiler is meant to be shared between the runtime image and the compiler images. This makes the presubmit build the nodejs runtime image first then builds the compiler images, which matches what would happen in a periodic update.

Run the base nodejs build before compiler in presubmit

---

jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-15-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-15-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-15-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-presubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-postsubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1-X-presubmits.yaml

The EKS Go builds will now also build a debian-based Golang image; prod jobs will push that image to public ECR. This add image builds to the EKS Go prow jobs, and adds the image push configuration for the prod public ECR to the prod post-submits.
Shoutout to @zafs23 for making it super easy to modify the EKS Go prow jobs w/https://github.com/aws/eks-distro-prow-jobs/pull/419

Add image build to golang jobs

---

jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-15-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml

update golang prod post-submits with fixed template
duplicated AWS_REGION in the prod post submits; remove the dupe.

update prod post-submits to not duplicate AWS_REGION env var for golang

---

jobs/aws/eks-distro-build-tooling/golang-1-15-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1-X-presubmits.yaml

We're building images with buildkit in the Go prow jobs, and will require more functionality than simply using the EKS Go base image provides. 

use standard builder-base image as the base for golang prow jobs

---

jobs/aws/eks-distro-build-tooling/golang-1-15-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1-X-presubmits.yaml

regenerate jobs
we don't need it now that we're using the builder base

remove make install from presubmit for golang

---

jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-15-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-15-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-postsubmits.yaml

use the builder-base for the Golang post-submits so that we can execute the image build for the `golang-debian` image. 
see https://github.com/aws/eks-distro-build-tooling/pull/667

use builder-base for golang post-submits

---

jobs/aws/eks-distro-build-tooling/aws-for-fluent-bit-helm-chart-presubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-make-tests.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-release-presubmits.yaml
jobs/aws/eks-distro-build-tooling/grafana-helm-chart-presubmits.yaml
jobs/aws/eks-distro-build-tooling/helm-chart-presubmits.yaml
jobs/aws/eks-distro-build-tooling/kops-presubmits.yaml
jobs/aws/eks-distro-build-tooling/prometheus-helm-chart-presubmits.yaml
jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml
jobs/aws/eks-distro/cni-1-21-presubmits.yaml
jobs/aws/eks-distro/cni-1-22-presubmits.yaml
jobs/aws/eks-distro/cni-1-23-presubmits.yaml
jobs/aws/eks-distro/cni-1-24-presubmits.yaml
jobs/aws/eks-distro/eks-distro-docs-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-22-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-23-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-24-test-presubmits.yaml
jobs/aws/eks-distro/main-presubmits.yaml
templater/templates/presubmits.yaml

For nonimage builds we werent creating the status/done file. This is now needed for the disk-usage sidecar

Fixes status/done handling for non-image builds

---

jobs/aws/eks-distro-build-tooling/golang-1-15-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-images-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-images-postsubmits.yaml

we don't need 16Gi to build these images. Mirroring the builder-base post-submit.

Reduce go image resources

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-test-presubmits.yaml
linter/main.go
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-test-presubmits.yaml

Add a check function to the Prow linter that checks whether job names have been duplicated in the latest changes.

Add duplicate job name check in linter

---

jobs/aws/eks-distro/aws-cloud-controller-manager-1-25-presubmits.yaml
jobs/aws/eks-distro/aws-iam-authenticator-1-25-presubmits.yaml
jobs/aws/eks-distro/build-1-25-postsubmits.yaml
jobs/aws/eks-distro/cni-1-25-presubmits.yaml
jobs/aws/eks-distro/coredns-1-25-presubmits.yaml
jobs/aws/eks-distro/dev-release-1-25-postsubmits.yaml
jobs/aws/eks-distro/etcd-1-25-presubmits.yaml
jobs/aws/eks-distro/external-attacher-1-25-presubmits.yaml
jobs/aws/eks-distro/external-provisioner-1-25-presubmits.yaml
jobs/aws/eks-distro/external-resizer-1-25-presubmits.yaml
jobs/aws/eks-distro/external-snapshotter-1-25-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-25-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-25-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-release-1-25-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-25-presubmits.yaml
jobs/aws/eks-distro/metrics-server-1-25-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-25-presubmits.yaml
jobs/aws/eks-distro/prod-release-1-25-postsubmits.yaml
templater/jobs/utils/utils.go

For the latest release branch we could check if the folder exists for the current project before trying to build.  This is similar to what we use PROJECT_PATH for in eks-a ([ex](https://github.com/aws/eks-anywhere-prow-jobs/blob/main/jobs/aws/eks-anywhere-build-tooling/autoscaler-1-23-presubmits.yaml#L50)).  This will allow us to check in new 1-25 jobs so we can test projects on eks-distro without breaking all other PRs until all the projects have had their 1-25 versions added

Adds checks for release branch directory

---

templater/jobs/postsubmit/eks-distro/build-1-X-postsubmits.yaml

Updates the list of files that will skip running the postsubmit jobs in our CI, which will lead to less resource usage/contention for changes that do need postsubmits

Update list of files that skip postsubmits

---

jobs/aws/eks-distro-build-tooling/prow-plugin-presubmit.yaml
templater/jobs/presubmit/eks-distro-build-tooling/prow-plugin-presubmit.yaml

Change the make target from build to images to build and produce the image without pushing the image in the presubmit. 

Update prow plugin presubmit

---

jobs/aws/eks-distro-build-tooling/golang-1-15-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml

golang image build now supports both the prod release and the prod images release for the golang debian image; this sets up the prow job to also support this.
Part of https://github.com/aws/eks-distro-build-tooling/pull/865

add updated eks go post-submits with image build

---

jobs/aws/eks-distro/aws-cloud-controller-manager-1-26-presubmits.yaml
jobs/aws/eks-distro/aws-iam-authenticator-1-26-presubmits.yaml
jobs/aws/eks-distro/build-1-26-postsubmits.yaml
jobs/aws/eks-distro/cni-1-26-presubmits.yaml
jobs/aws/eks-distro/coredns-1-26-presubmits.yaml
jobs/aws/eks-distro/dev-release-1-26-postsubmits.yaml
jobs/aws/eks-distro/etcd-1-26-presubmits.yaml
jobs/aws/eks-distro/external-attacher-1-26-presubmits.yaml
jobs/aws/eks-distro/external-provisioner-1-26-presubmits.yaml
jobs/aws/eks-distro/external-resizer-1-26-presubmits.yaml
jobs/aws/eks-distro/external-snapshotter-1-26-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-26-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-26-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-release-1-26-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-26-presubmits.yaml
jobs/aws/eks-distro/metrics-server-1-26-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-26-presubmits.yaml
jobs/aws/eks-distro/prod-release-1-26-postsubmits.yaml
linter/main.go
templater/jobs/utils/utils.go

Since we are using the templater as a libary over in eks-a-prow-jobs, the release branch directory check is bleeding over to some of the [jobs](https://github.com/aws/eks-anywhere-prow-jobs/blob/main/jobs/aws/eks-anywhere-build-tooling/imagebuilder-1-26-presubmits.yaml#L49) there.  Some of the builds in eks-a do not have release branch folders, yet are "release branched". 
This PR changes the prow jobs to instead call a make target vs simply checking for the existence of the folder.  This chekc is added [here](https://github.com/aws/eks-distro/pull/1844/files#diff-6daeb9c300098022af9eb1c5f69e52ffbd840490fd9945ac9c3e2d02ad838ab7R963) and for eks-d is just the folder check.
For eks-a, we can change the …

Changes release branch check

---

jobs/aws/eks-distro/kubernetes-1-22-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-23-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-24-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-25-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-26-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-27-test-presubmits.yaml
templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml

Same changes as https://github.com/aws/eks-distro-prow-jobs/pull/501 but to different jobs. We keep getting out-of-space failures on https://github.com/aws/eks-distro/pull/1956 

Increased resources on k8s presubmit test

---

jobs/aws/eks-distro/aws-cloud-controller-manager-1-23-presubmits.yaml
jobs/aws/eks-distro/aws-iam-authenticator-1-23-presubmits.yaml
jobs/aws/eks-distro/build-1-23-postsubmits.yaml
jobs/aws/eks-distro/build-1-24-postsubmits.yaml
jobs/aws/eks-distro/build-1-26-postsubmits.yaml
jobs/aws/eks-distro/build-1-27-postsubmits.yaml
jobs/aws/eks-distro/build-1-28-postsubmits.yaml
jobs/aws/eks-distro/cni-1-23-presubmits.yaml
jobs/aws/eks-distro/coredns-1-23-presubmits.yaml
jobs/aws/eks-distro/dev-release-1-23-postsubmits.yaml
jobs/aws/eks-distro/etcd-1-23-presubmits.yaml
jobs/aws/eks-distro/external-attacher-1-23-presubmits.yaml
jobs/aws/eks-distro/external-provisioner-1-23-presubmits.yaml
jobs/aws/eks-distro/external-resizer-1-23-presubmits.yaml
jobs/aws/eks-distro/external-snapshotter-1-23-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-23-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-23-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-release-1-23-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-23-presubmits.yaml
jobs/aws/eks-distro/metrics-server-1-23-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-23-presubmits.yaml
jobs/aws/eks-distro/prod-release-1-23-postsubmits.yaml
templater/jobs/utils/utils.go

This reverts commit 90d5f88ee7f1e2ec5940a3b4ae1cac1991cab845.
Revert https://github.com/aws/eks-distro-prow-jobs/pull/526

Revert "Remove 1.23 prowjobs (#526)"

---

jobs/aws/eks-distro/kubernetes-1-28-test-presubmits.yaml
linter/main.go
templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml
templater/jobs/types/types.go
templater/templates/presubmits.yaml

Request ephemeral storage to run 1-28-test-presubmit on fargate

---

jobs/aws/eks-distro/kubernetes-1-28-test-presubmits.yaml
templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml
templater/jobs/types/types.go
templater/templates/presubmits.yaml

*Description of changes:* 
This change changes ephemeralStorage field to ephemeral-storage to be a standard resource

Configure ephemeral storage to be a standard resource

---

jobs/aws/eks-distro/kubernetes-1-27-test-presubmits.yaml
linter/main.go
templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml

Request ephemeral-storage for 1-27-test-presubmit

---

jobs/aws/eks-distro-build-tooling/kops-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/kops-presubmits.yaml

[Kops-Presubmit jobs](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/1141/kops-tooling-presubmit/1703871240634109952) are failing in eks-distro-build-tooing this should bump the storage to allow the jobs to complete

Update storage size for kops-presubmits

---

jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-21-PROD-images-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-images-postsubmits.yaml

The debian releases are still failing due to not having correct permissions. Comparing the differences between the nonDebian sns message and debian sns message is the service account used. Similar to https://github.com/aws/eks-distro-prow-jobs/pull/377

Update service account similar to access artifact account

---

templater/jobs/types/types.go
templater/main.go
templater/templates/presubmits.yaml

We want to try running our image builder presubmits in eks-a as the imagebuilder user to try and catch things that bite us in codebuild.

adds support for setting runAsUser and runAsGroup

---

templater/scripts/verify-prowjobs.sh

Exclude 1-23 jobs from Prowjob Linter

---

templater/jobs/utils/utils.go
templater/scripts/verify-prowjobs.sh

We need to track the list of unsupported branches for which we sync k8 patches. To test these patches the `kubernetes-presubmit` and `kubernetes-presubmit-test` prowjobs are needed.  
Adding a new list of branches called the `k8releaseBranches` will help to track these branches which are unsupported versions but for which k8 patches are synced with EKS. 
Pair PR in EKS-Distro: https://github.com/aws/eks-distro/pull/2642

Generalize supported branches for K8 patches

---

jobs/aws/eks-distro/eks-distro-attribution-periodics.yaml
templater/jobs/periodic/eks-distro/eks-distro-attribution-periodics.yaml

We recently added a big patch that vendored deps, which caused the clean up command to fail because the .git file was still in use likely due to a race between the git gc and clean up of some huge patch files. 

Turn off auto garbage collection to help with big patches

---

config/docker-ecr-config.json

We need this to be able to use the build account ECR cache in EKS-A presubmits.

Add EKS-A build account to Prow cred helpers config

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-24-al-2.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-24-al-2023.yaml
jobs/aws/eks-distro-build-tooling/golang-1-24-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-24-presubmits.yaml
templater/jobs/utils/utils.go

Deprecated go lang 1.22 and added 1.24

Deprecated go lang 1.22 and added 1.24

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-windows.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-windows.yaml

Prow jobs are failing with `no space left on device`, refer [prow job logs.](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/1696/eks-distro-base-tooling-presubmits-windows/1919404211620024320#2:build-container-build-log.txt%3A827). This error started after adding support to build WS2025 container image.
This [PR](https://github.com/aws/eks-distro-build-tooling/pull/1696) add support to building Windows Server 2025 container images. Unfortuntanely, prow jobs are failing with `no space left on device`, refer [prow job logs](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-d …

Increase disk space when building Windows Container image

---

linter/Makefile

set linter to use go 1.23

---

.github/workflows/builder-baseimage-pr-notifier.yml

- Move PR title to environment variable to prevent shell injection
- Maintains identical functionality

fix: prevent script injection in base-image-pr-notifier
