aws/eks-distro-prow-jobs

jobs/aws/eks-distro/docs-postsubmit.yaml

Update docs postsubmit to use docs-build-account

Update docs postsubmit to use docs-build-account

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml

Correct script name in periodic job.

Fix script name in EKS Distro base periodic

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml

Testing by running periodic at 11.30

Change cron to test latest PR script changes

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml

Run cron periodic every 10 mins

---

jobs/aws/eks-distro-build-tooling/athens-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/athens-presubmits.yaml

Pre and Post submit jobs for Athens

---

jobs/aws/eks-distro-build-tooling/athens-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/athens-presubmits.yaml

Add image build label for athens

---

jobs/aws/eks-distro-build-tooling/athens-postsubmits.yaml

Use proper post submit service account for Athens

---

jobs/aws/eks-distro-build-tooling/athens-postsubmits.yaml

Tag athens image with commit hash

---

jobs/presets.yaml

Set GOPROXY env variable for Athens

---

jobs/presets.yaml

This reverts commit b2e47082fbcd420e594015ef1d219431db9e5b20, reversing
changes made to 94312b008fec90c1ad798c665ec7785fca0192e0.

Revert "Merge pull request #39 from bnrjee/env_var"

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml

Dry-run for check_update script via presubmit.

Modify presubmit to dryrun yum check-update

---

jobs/presets.yaml

Not needed anymore due to this PR: https://github.com/aws/eks-distro-build-tooling/pull/58
Shouldn't be merged until we merge the CDK changes.
/hold

Remove AWS_STS_REGIONAL_ENDPOINTS from presets

---

jobs/presets.yaml

Set GOPROXY to use Athens proxy

---

go.mod
scripts/lint_prowjobs/main.go

Added Prowjob linting logic for presubmits and postsubmits.
Had to create a new PR for linting as I pushed to the closed [PR](https://github.com/aws/eks-distro-prow-jobs/pull/58) by mistake.

Add linting script for prowjobs

---

jobs/aws/eks-distro/kops-build-postsubmit.yaml
jobs/presets.yaml

Prow job for kops build testing

---

jobs/aws/eks-distro-build-tooling/aws-for-fluent-bit-helm-chart-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/aws-for-fluent-bit-helm-chart-presubmits.yaml

Prow jobs for aws-for-fluent-bit helm chart

---

jobs/aws/eks-distro-build-tooling/aws-for-fluent-bit-helm-chart-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/aws-for-fluent-bit-helm-chart-presubmits.yaml

Fix prow job files for aws-fluent-bit

---

OWNERS

Add entire team to owners file

Add entire team to owners

---

jobs/presets.yaml

Set AWS_ROLE_SESSION_NAME without any label

---

scripts/lint_prowjobs/main.go

Postsubmit make target checks were defaulting to check against the `release` target. This will cause the main postsubmit to fail, since it uses the `postsubmit-conformance` target. Added a separate check against the job name to enable the linting to pass.
Also some PR's ([example](https://github.com/aws/eks-distro-prow-jobs/pull/79)) might delete the jobs, so the files will still show up in the `git diff`, but the lint script will not be able to find them in the file system. Hence we need a check to see if file does not exist and skip linting on those jobs.

Add make target check for main postsubmit, skip linting if file does not exist

---

jobs/aws/eks-distro/main-1-18-postsubmits.yaml
jobs/aws/eks-distro/main-1-19-postsubmits.yaml

Add 1-19 main post submit

---

scripts/lint_prowjobs/main.go

This PR will fix the linting failure in https://github.com/aws/eks-distro-prow-jobs/pull/90.

Fix postsubmit make target check for release postsubmit

---

scripts/lint_prowjobs/main.go

Skip make release target check for release postsubmits

---

jobs/aws/eks-distro/release-1-18-postsubmits.yaml
jobs/aws/eks-distro/release-1-19-postsubmits.yaml

Add postsubmits for release

---

jobs/aws/eks-distro/release-1-18-postsubmits.yaml
jobs/aws/eks-distro/release-1-19-postsubmits.yaml

Modify prow jobs for release

---

jobs/aws/eks-distro/release-1-18-postsubmits.yaml
jobs/aws/eks-distro/release-1-19-postsubmits.yaml

Fix release jobs

---

jobs/aws/eks-distro/public-release-1-18-postsubmits.yaml
jobs/aws/eks-distro/public-release-1-19-postsubmits.yaml

Add prow job for public release

---

jobs/aws/eks-distro/main-1-18-postsubmits.yaml
jobs/aws/eks-distro/main-1-19-postsubmits.yaml

Disable conformance to reduce contention

---

jobs/aws/eks-distro/public-release-1-18-postsubmits.yaml
jobs/aws/eks-distro/public-release-1-19-postsubmits.yaml
jobs/aws/eks-distro/release-1-18-postsubmits.yaml
jobs/aws/eks-distro/release-1-19-postsubmits.yaml

Use environment variables for jobs

---

jobs/aws/eks-distro/dev-release-1-18-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-19-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-18-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-19-postsubmits.yaml

Hopefully these names will make it a bit more clear what they do.

Rename release jobs

---

jobs/aws/eks-distro/build-1-18-postsubmits.yaml
jobs/aws/eks-distro/build-1-19-postsubmits.yaml

Add DOCKER_CONFIG in build jobs

---

jobs/aws/eks-distro/main-presubmits.yaml

Run main pre-submit when cmd/ folder changes

---

jobs/aws/eks-distro/build-1-18-postsubmits.yaml
jobs/aws/eks-distro/build-1-19-postsubmits.yaml

Add public repo uri as env variable

---

jobs/aws/eks-distro/dev-release-1-20-postsubmits.yaml
jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml

Add 1-20 pre and post submit jobs

Add 1-20 jobs

---

jobs/aws/eks-distro/announcement-postsubmits.yaml
scripts/lint_prowjobs/main.go

Add announcement postsubmit

---

jobs/aws/eks-distro/attribution-files-periodics.yaml

run attribution generation once a day

---

jobs/aws/eks-distro/build-1-18-postsubmits.yaml
jobs/aws/eks-distro/build-1-19-postsubmits.yaml
jobs/aws/eks-distro/build-1-20-postsubmits.yaml

Increase time out for build jobs pods

---

jobs/aws/eks-distro/aws-iam-authenticator-1-20-presubmits.yaml
jobs/aws/eks-distro/coredns-1-20-presubmits.yaml
jobs/aws/eks-distro/metrics-server-1-20-presubmits.yaml

Added jobs for components. Related PR: https://github.com/aws/eks-distro/pull/239

Added component tests for 1-20

---

jobs/aws/eks-distro/build-1-18-postsubmits.yaml
jobs/aws/eks-distro/build-1-19-postsubmits.yaml
jobs/aws/eks-distro/build-1-20-postsubmits.yaml

Remove REPOSITORY_URI from jobs

---

jobs/aws/eks-distro/build-1-18-postsubmits.yaml
jobs/aws/eks-distro/build-1-19-postsubmits.yaml
jobs/aws/eks-distro/build-1-20-postsubmits.yaml

Use k8s specific instance profile roles to run kops

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml

Fix indentation error in prowjob YAML

Fix indentation in periodic job

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

Source the script so that it rruns in the same bash shell.

Source ECR setup script instead of running it

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml

Remove duplicate env section in prowjob

Fix env vars section in periodic

---

jobs/aws/eks-distro/build-1-21-postsubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml

Added build-1-21-postsubmits and presubmits jobs

---

jobs/aws/eks-distro/build-1-21-postsubmits.yaml

Changed kops role for 1.21

---

jobs/aws/eks-distro/kubernetes-1-18-release-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-19-release-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-20-release-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-release-presubmits.yaml

kubernetes/release: introduce release branches

---

jobs/aws/eks-distro/build-1-18-postsubmits.yaml
jobs/aws/eks-distro/build-1-19-postsubmits.yaml
jobs/aws/eks-distro/build-1-20-postsubmits.yaml
jobs/aws/eks-distro/build-1-21-postsubmits.yaml

Run kops jobs with same instance profiles

---

jobs/aws/eks-distro/build-1-21-arm64-postsubmits.yaml

Fix instance profiles to run kops on arm

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml

Signed-off-by: Micah Hausler <mhausler@amazon.com>
N/A
These calls will work after aws/eks-distro-build-tooling#184 and aws/eks-distro#459 are merged

Added minimal base makefile calls

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml

Removed comments from multiline bash

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml

distro-base: use build target which will build all variants

---

jobs/aws/eks-distro/build-1-21-minimal-postsubmits.yaml

add minimal postsubmit to build 1-21 using new minimal base

---

jobs/aws/eks-distro/build-1-21-minimal-postsubmits.yaml

add overrides for minimal builds

---

jobs/aws/eks-distro/build-1-18-minimal-postsubmits.yaml
jobs/aws/eks-distro/build-1-19-minimal-postsubmits.yaml
jobs/aws/eks-distro/build-1-20-minimal-postsubmits.yaml
jobs/aws/eks-distro/build-1-21-minimal-arm64-postsubmits.yaml

1-21 passed... adding the other versions

add additional minimal postsubmits

---

jobs/aws/eks-distro/build-1-21-minimal-postsubmits.yaml
jobs/aws/eks-distro/build-1-21-postsubmits.yaml
scripts/lint_prowjobs/main.go

1-21 postsubmit run arm and amd in parallel

---

jobs/aws/eks-distro/eks-distro-docs-postsubmits.yaml
jobs/aws/eks-distro/eks-distro-docs-presubmits.yaml

Add reponame to docs Prowjob name

Rename docs prowjobs to avoid conflict

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml
jobs/presets.yaml

fix preset for registry-script

---

jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml

kubernetes: local registry for go-runner + proxy base images

---

jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml

kubernetes: push to local reg

---

jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml

kubernetes: clean after build release project

---

jobs/aws/eks-distro/metrics-server-1-19-presubmits.yaml

metrics-server 1.19: fix formatting

---

jobs/aws/eks-distro/prod-release-1-20-postsubmits.yaml

Fixing YAML indentation on postsubmit.

Fix indentation on prod release postsubmit

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

Scope down postsubmits trigger to this single file.

Run postsubmits only on changes to trigger file

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits.yaml

add builds for al2022 based eks-distro-base

---

docs/prowjobs.md

Fix minor error in docs

---

jobs/aws/eks-distro/main-presubmits.yaml
templater/jobs/presubmit/eks-distro/main-presubmits.yaml

main-presubmit is just a dry run at this point, dropping resources

---

templater/main.go

The templater had a bug where when templates get deleted, the corresponding jobs do not get deleted. This should fix it.

Delete jobs if templates are deleted

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmit-2022.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmit-2022.yaml

I had intended to override this in the Makefile but make doesnt let you override vars passed in via the command line like this...

eks-distro-base: appened al_tag in prow job

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

bump eks-distro-base job timeouts

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml

builder-base: add 2022 builds

---

jobs/aws/eks-distro/external-attacher-1-18-presubmits.yaml
jobs/aws/eks-distro/external-attacher-1-19-presubmits.yaml
jobs/aws/eks-distro/external-attacher-1-20-presubmits.yaml
jobs/aws/eks-distro/external-attacher-1-21-presubmits.yaml
jobs/aws/eks-distro/external-attacher-1-22-presubmits.yaml
templater/jobs/presubmit/eks-distro/external-attacher-1-X-presubmits.yaml

fix additional jobname in external-attacher job

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

These jobs take forever to run with no resource requests, seeing if this will speed things up.

Add more resources to eks-distro-base postsubmits

---

config/docker-ecr-config.json

add snow ecr to docker login

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

distro-base: bump timeout on postsubmit and periodic

---

docs/prowjobs.md
jobs/aws/eks-distro/build-1-19-postsubmits.yaml
jobs/aws/eks-distro/build-1-20-postsubmits.yaml
jobs/aws/eks-distro/build-1-21-postsubmits.yaml
jobs/aws/eks-distro/build-1-22-postsubmits.yaml
templater/jobs/postsubmit/eks-distro/build-1-X-postsubmits.yaml
templater/jobs/types/types.go
templater/jobs/utils/utils.go
templater/main.go
templater/templates/postsubmits.yaml

* Add skip to postsubmit builds

Added skip_if_only_changed to postsubmit builds

---

jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml

Bump resources for builder-base presubmits

---

jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml

Fixes issue with pod not starting on Fargate.

Fix resources for builder-base presubmits

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml

Show debug log during eks-distro images build

---

jobs/aws/eks-distro-build-tooling/golang-1.15-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1.15-presubmits.yaml

fix make call path in go prow job

Fix go prow job make call

---

jobs/aws/eks-distro-build-tooling/golang-1.15-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1.15-presubmits.yaml

we need to install make on al2

update prow job to install make on al2

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-compiler-base-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-compiler-base-2022.yaml

Fixes compiler base 2022 job

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-compiler-base-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-compiler-base.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-java-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-compiler-base-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-compiler-base.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-java-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9.yaml

Adds new compiler jobs for nodejs/golang

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-java-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-java.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-java-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-java.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9.yaml

Fixes python for older PRs and cleans up new jobs

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-make-tests.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-make-tests.yaml

Fixes eks-distro-base make-tests presubmit

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml

Fixes python3.9 presubmit

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml

Prune buildctl for golang 116

---

jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml

Switches builder-base job to use al2

---

jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml

Increases requests on builder-base presubmits

---

jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/templates/presubmits.yaml

Use amd64 nodes for builder-base presubmit

---

jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-buildx-postsubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/templates/postsubmits.yaml
templater/templates/presubmits.yaml

Adds buildx for builder-base presubmit

---

jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml

Switch builder-base builder image to builder-base again

---

jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/templates/presubmits.yaml

Automounts sa for builder base

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml

Adds resources to builder base presubmit

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics.yaml

Use postsubmits-build-account for periodici distro-base jobs

---

scripts/buildkitd-entrypoint.sh

Gives buildkitd more cache on postsubmit

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-make-tests.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-make-tests.yaml

Adds resources request to make-tests pre

---

jobs/aws/eks-distro/eks-distro-attribution-periodics.yaml
templater/jobs/periodic/eks-distro/eks-distro-attribution-periodics.yaml

https://github.com/aws/eks-anywhere-prow-jobs/pull/222

Renames attribution job

---

jobs/aws/eks-distro/livenessprobe-1-21-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-22-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-23-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-24-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-21-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-22-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-23-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-24-presubmits.yaml
templater/jobs/presubmit/eks-distro/livenessprobe-1-X-presubmits.yaml
templater/jobs/presubmit/eks-distro/node-driver-registrar-1-X-presubmits.yaml

Run images target for livenessprobe and registrar

---

jobs/aws/eks-distro/aws-cloud-controller-manager-1-21-presubmits.yaml
jobs/aws/eks-distro/aws-cloud-controller-manager-1-22-presubmits.yaml
jobs/aws/eks-distro/aws-cloud-controller-manager-1-23-presubmits.yaml
jobs/aws/eks-distro/aws-cloud-controller-manager-1-24-presubmits.yaml
templater/jobs/presubmit/eks-distro/aws-cloud-controller-manager-1-X-presubmits.yaml

Adds local registry to ccm presubmit

---

jobs/aws/eks-distro/livenessprobe-1-21-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-22-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-23-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-24-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-21-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-22-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-23-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-24-presubmits.yaml
templater/jobs/presubmit/eks-distro/livenessprobe-1-X-presubmits.yaml
templater/jobs/presubmit/eks-distro/node-driver-registrar-1-X-presubmits.yaml

Cleans after images for sidecar windows images

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml

Decreases request for builder-base bulds

---

jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-15-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-postsubmits.yaml

We want to run the EKS Go post-submits when the EKS Go makefile changes.

Run eks go post on make change

---

jobs/aws/eks-distro-build-tooling/aws-for-fluent-bit-helm-chart-presubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-make-tests.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-release-presubmits.yaml
jobs/aws/eks-distro-build-tooling/grafana-helm-chart-presubmits.yaml
jobs/aws/eks-distro-build-tooling/helm-chart-presubmits.yaml
jobs/aws/eks-distro-build-tooling/kops-presubmits.yaml
jobs/aws/eks-distro-build-tooling/prometheus-helm-chart-presubmits.yaml
jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml
jobs/aws/eks-distro/cni-1-21-presubmits.yaml
jobs/aws/eks-distro/cni-1-22-presubmits.yaml
jobs/aws/eks-distro/cni-1-23-presubmits.yaml
jobs/aws/eks-distro/cni-1-24-presubmits.yaml
jobs/aws/eks-distro/eks-distro-docs-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-22-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-23-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-24-test-presubmits.yaml
jobs/aws/eks-distro/main-presubmits.yaml
templater/templates/presubmits.yaml

Missed this on some of the jobs that didnt already have labels.

Fixes disk-usage label missing from prow jobs

---

jobs/aws/eks-distro-build-tooling/aws-for-fluent-bit-helm-chart-presubmits.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-make-tests.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-release-presubmits.yaml
jobs/aws/eks-distro-build-tooling/grafana-helm-chart-presubmits.yaml
jobs/aws/eks-distro-build-tooling/helm-chart-presubmits.yaml
jobs/aws/eks-distro-build-tooling/kops-presubmits.yaml
jobs/aws/eks-distro-build-tooling/prometheus-helm-chart-presubmits.yaml
jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml
jobs/aws/eks-distro/cni-1-21-presubmits.yaml
jobs/aws/eks-distro/cni-1-22-presubmits.yaml
jobs/aws/eks-distro/cni-1-23-presubmits.yaml
jobs/aws/eks-distro/cni-1-24-presubmits.yaml
jobs/aws/eks-distro/eks-distro-docs-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-21-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-22-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-23-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-24-test-presubmits.yaml
jobs/aws/eks-distro/main-presubmits.yaml
templater/templates/presubmits.yaml

Fixes missing && for status/done trap

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-windows.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-windows.yaml

Fixes windows base presubmit

---

jobs/aws/eks-distro/livenessprobe-1-21-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-22-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-23-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-24-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-21-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-22-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-23-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-24-presubmits.yaml
templater/jobs/presubmit/eks-distro/livenessprobe-1-X-presubmits.yaml
templater/jobs/presubmit/eks-distro/node-driver-registrar-1-X-presubmits.yaml

Goes with: https://github.com/aws/eks-distro/pull/1569

Runs livenessprobe/node-registrar on presubmit cluster

---

linter/main.go

Skip go make lint check

---

jobs/aws/eks-distro/build-1-21-postsubmits.yaml
jobs/aws/eks-distro/build-1-22-postsubmits.yaml
jobs/aws/eks-distro/build-1-23-postsubmits.yaml
jobs/aws/eks-distro/build-1-24-postsubmits.yaml
jobs/aws/eks-distro/build-1-25-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-21-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-22-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-23-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-24-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-25-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-21-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-22-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-23-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-24-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-25-postsubmits.yaml
templater/jobs/postsubmit/eks-distro/build-1-X-postsubmits.yaml
templater/jobs/postsubmit/eks-distro/dev-release-1-X-postsubmits.yaml
templater/jobs/postsubmit/eks-distro/prod-release-1-X-postsubmits.yaml
templater/jobs/utils/utils.go

Sets project_path for postsubmits to fix directory verification

---

jobs/aws/eks-distro-build-tooling/golang-1-15-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-16-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-17-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-presubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-presubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1-X-presubmits.yaml

We want to make sure we run the EKS Go pre-submits on changes to the EKS Go Debian image.

Adjust eks go prow jobs

---

jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-al-2.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-al-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3-7-al-2.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3-7-al-2022.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3-9-al-2.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3-9-al-2022.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-al-X.yaml
templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3-X-al-X.yaml

Build python runtime image to match nodejs jobs

---

jobs/aws/eks-distro/build-1-21-postsubmits.yaml
jobs/aws/eks-distro/build-1-22-postsubmits.yaml
jobs/aws/eks-distro/build-1-23-postsubmits.yaml
jobs/aws/eks-distro/build-1-24-postsubmits.yaml
jobs/aws/eks-distro/build-1-25-postsubmits.yaml
jobs/aws/eks-distro/build-1-26-postsubmits.yaml
templater/jobs/postsubmit/eks-distro/build-1-X-postsubmits.yaml

Excludes go.mod and go.sum files from the postsubmit trigger. We don't need these to run the postsubmits.

Exclude go mod and sum

---

jobs/aws/eks-distro-build-tooling/golang-1-20-ARM64-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-ARM64-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-presubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-images-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-postsubmits.yaml
templater/jobs/presubmit/eks-distro-build-tooling/golang-1-X-presubmits.yaml

Fixed golang 1.20 jobs and bug in template

---

jobs/aws/eks-distro-build-tooling/prow-plugin-postsubmit.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/prow-plugin-postsubmit.yaml

Created prow plugin postsubmit to push artifacts to ECR. Update presubmit to use correct make target in build tooling.

Update Presubmit and Create Postsubmit for Prow Plugin

---

jobs/aws/eks-distro-build-tooling/prow-plugin-postsubmit.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/prow-plugin-postsubmit.yaml

Add required source and values to push to [public ecr](https://gallery.ecr.aws/eks-distro-build-tooling/eks-distro-ops-tool)

Add envs to ProwPluginPostsubmit

---

jobs/aws/eks-distro-build-tooling/prow-plugin-postsubmit.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/prow-plugin-postsubmit.yaml

Follow a release target for postsubmit to push to ECR.

update plugin postsubmit to track RELEASE file

---

jobs/aws/eks-distro/aws-cloud-controller-manager-1-26-presubmits.yaml
jobs/aws/eks-distro/aws-iam-authenticator-1-26-presubmits.yaml
jobs/aws/eks-distro/build-1-26-postsubmits.yaml
jobs/aws/eks-distro/cni-1-26-presubmits.yaml
jobs/aws/eks-distro/coredns-1-26-presubmits.yaml
jobs/aws/eks-distro/dev-release-1-26-postsubmits.yaml
jobs/aws/eks-distro/etcd-1-26-presubmits.yaml
jobs/aws/eks-distro/external-attacher-1-26-presubmits.yaml
jobs/aws/eks-distro/external-provisioner-1-26-presubmits.yaml
jobs/aws/eks-distro/external-resizer-1-26-presubmits.yaml
jobs/aws/eks-distro/external-snapshotter-1-26-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-26-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-26-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-release-1-26-presubmits.yaml
jobs/aws/eks-distro/livenessprobe-1-26-presubmits.yaml
jobs/aws/eks-distro/metrics-server-1-26-presubmits.yaml
jobs/aws/eks-distro/node-driver-registrar-1-26-presubmits.yaml
jobs/aws/eks-distro/prod-release-1-26-postsubmits.yaml
templater/jobs/utils/utils.go

Fix release branch check

---

jobs/aws/eks-distro/kubernetes-1-22-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-23-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-24-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-25-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-26-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-27-presubmits.yaml
templater/jobs/presubmit/eks-distro/kubernetes-1-X-presubmits.yaml

bumps kubernetes presubmit resources up

---

OWNERS

Added new people to OWNERS

---

.github/workflows/builder-baseimage-pr-notifier.yml

Add builder-base image PR notifier

---

jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-images-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml

Added sns notification to golang post-submits

---

jobs/aws/eks-distro/kubernetes-1-28-test-presubmits.yaml
linter/main.go
templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml

Move 1-28-test-presubmits job to different cluster

---

jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-21-PROD-images-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-images-postsubmits.yaml

Added role to golang image updates

---

go.mod

Fix go.mod for linter

---

jobs/aws/eks-distro/kubernetes-1-25-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-26-test-presubmits.yaml
templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml

Fix storage issues facing : https://github.com/aws/eks-distro/pull/2392

Request ephemeral storage to run 1.25,1.26 test presubmits

---

jobs/aws/eks-distro-build-tooling/builder-base-postsubmits-al-2.yaml
jobs/aws/eks-distro-build-tooling/builder-base-postsubmits-al-2023.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics-al-2.yaml
jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics-al-2023.yaml
templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics-al-X.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits-al-X.yaml

Set max concurrency to 1 for Builder-Base postsubmit

---

jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-images-postsubmits.yaml
jobs/aws/eks-distro-build-tooling/golang-1-21-PROD-images-postsubmits.yaml
templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-images-postsubmits.yaml

Reverts aws/eks-distro-prow-jobs#555

Revert "Update service account similar to access artifact account"

---

templater/scripts/verify-prowjobs.sh

Update verify_prowjob script

---

jobs/aws/eks-distro/cni-1-24-test-presubmits.yaml
jobs/aws/eks-distro/cni-1-25-test-presubmits.yaml
jobs/aws/eks-distro/cni-1-26-test-presubmits.yaml
jobs/aws/eks-distro/cni-1-27-test-presubmits.yaml
jobs/aws/eks-distro/cni-1-28-test-presubmits.yaml
templater/jobs/presubmit/eks-distro/cni-1-X-test-presubmits.yaml

Update CNI-plugin unit tests triggers

---

jobs/aws/eks-distro/kubernetes-1-29-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-30-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-31-test-presubmits.yaml
templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml

increase ephemeral storage for k8s 1.29-1.31 test presubmits

---

jobs/aws/eks-distro/kubernetes-1-33-test-presubmits.yaml
templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml

Add 1.33 to get ephemeral storage

---

OWNERS

Add charles-large to owners

---

jobs/aws/eks-distro/aws-cloud-controller-manager-1-33-presubmits.yaml
jobs/aws/eks-distro/aws-cloud-controller-manager-1-34-presubmits.yaml
jobs/aws/eks-distro/aws-iam-authenticator-1-33-presubmits.yaml
jobs/aws/eks-distro/aws-iam-authenticator-1-34-presubmits.yaml
jobs/aws/eks-distro/build-1-28-postsubmits.yaml
jobs/aws/eks-distro/build-1-30-postsubmits.yaml
jobs/aws/eks-distro/build-1-31-postsubmits.yaml
jobs/aws/eks-distro/build-1-32-postsubmits.yaml
jobs/aws/eks-distro/build-1-33-postsubmits.yaml
jobs/aws/eks-distro/build-1-34-postsubmits.yaml
jobs/aws/eks-distro/cni-1-33-presubmits.yaml
jobs/aws/eks-distro/cni-1-34-presubmits.yaml
jobs/aws/eks-distro/coredns-1-33-presubmits.yaml
jobs/aws/eks-distro/coredns-1-34-presubmits.yaml
jobs/aws/eks-distro/dev-release-1-33-postsubmits.yaml
jobs/aws/eks-distro/dev-release-1-34-postsubmits.yaml
jobs/aws/eks-distro/etcd-1-33-presubmits.yaml
jobs/aws/eks-distro/etcd-1-34-presubmits.yaml
jobs/aws/eks-distro/kops-build-1-33-presubmits.yaml
jobs/aws/eks-distro/kops-build-1-34-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-33-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-33-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-34-presubmits.yaml
jobs/aws/eks-distro/kubernetes-1-34-test-presubmits.yaml
jobs/aws/eks-distro/kubernetes-release-1-33-presubmits.yaml
jobs/aws/eks-distro/kubernetes-release-1-34-presubmits.yaml
jobs/aws/eks-distro/prod-release-1-33-postsubmits.yaml
jobs/aws/eks-distro/prod-release-1-34-postsubmits.yaml
templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml
templater/jobs/utils/utils.go

Added jobs for 1.34

---

jobs/aws/eks-distro/eks-distro-attribution-periodics.yaml
templater/jobs/periodic/eks-distro/eks-distro-attribution-periodics.yaml

add buildkit to attribution periodic

---

jobs/aws/eks-distro/eks-distro-attribution-periodics.yaml
templater/jobs/periodic/eks-distro/eks-distro-attribution-periodics.yaml

set image repo to dev release ECR for attribution periodic
